version: '3.8'

services:
  # 1. НАШ БЭКЕНД
  api:
    image: flowmarket-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowmarket_api
    restart: always
    ports:
      - "5009:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=flowmarket;Username=admin;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
      - AppUrl=http://localhost:5009
    depends_on:
      - db
    volumes:
      - ./uploads:/app/wwwroot/images # <--- Проброс папки для картинок

  # 2. БАЗА ДАННЫХ
  db:
    image: postgres:16-alpine
    container_name: flowmarket_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowmarket
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: