version: '3.8'

services:
  # 1. БЭКЕНД (API)
  api:
    image: flowmarket-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowmarket_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # ВАЖНО: Заменить IP реальный IP сервера!
      - AppUrl=http://№№№№
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=flowmarket;Username=admin;Password=password
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    volumes:
      # Картинки хранятся снаружи, чтобы не пропали
      - ./uploads:/app/wwwroot/images

  # 2. ФРОНТЕНД (Сайт)
  frontend:
    image: flowmarket-client
    build:
      context: ./flowmarket-client
      dockerfile: Dockerfile
    container_name: flowmarket_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

  # 3. БАЗА ДАННЫХ
  db:
    image: postgres:16-alpine
    container_name: flowmarket_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowmarket
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: